### PR TITLE
Add alifedata-phyloinformatics-convert info

### PR DESCRIPTION
**Pull request by mmore500**

### CODE REVIEW

**Comment by mmore500** [comment]
Closes #36 #37

**Comment by emilydolson** [comment]
This looks good! I made one super pedantic and annoying change (the three steps are technically for tracking a phylogeny, importing and exporting is sort of a different use pattern). I also tested the phyloinformatics convert code and made some minor fixes. We should probably add a test somewhere that enforces that it works.

One slight issue (not sure if this is in phylotrackpy or alife_phyloinformatics_convert): when you convert a tree to phylotrackpy using RosettaTree and then call `get_active_taxa()` on it, it returns a list of active taxa as it should. However, the active taxa subsequently get deleted somehow and the entire tree is broken.

Otherwise, I love RosettaTree! It looks great!

**Comment by emilydolson** [comment]
Okay, looks like this was an issue in phylotrackpy related to memory management when converting between C++ and python. I believe it is fixed now.

**Review by emilydolson — APPROVED** [review]
Looks great! Thanks!

**Pull request merged**
